### ISSUE TITLE
Epinano_variant.py terminated with no error message

### ISSUE THREAD

**Issue by BioinfoHub-PeiQinNg** [novoalab/EpiNano#112]
Hi there. I am trying to run EpiNano1.2 on some RNA direct data. When I check the log files of the submitted job for EpiNano_variant.py, it showed the following log with no error message.

`Process Process-2:
Traceback (most recent call last):
  File "/home/ng/localenv/miniconda3/envs/Epinano1.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ng/localenv/miniconda3/envs/Epinano1.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ng/localenv/EpiNano/Epinano_Variants.py", line 44, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration`

The code that I used to run EpiNano1.2 is as follow:
`python ~/localenv/EpiNano/Epinano_Variants.py \
		  -R {input.ref} \
		  -b {input.bam} \
		  -s /home/ng/localenv/EpiNano/misc/sam2tsv.jar \
		  -T g
`
Thank you. If you can help me with this that will be great!

**Comment by BioinfoHub-PeiQinNg** [comment]
A little bit more information on the issue:

I have looked at the previous thread #94 and tried the following command line:

`samtools view -h -F 3860 {bam_file} | java -jar  {sam2tsv} -r {reference_file}`


And this is the output I get:

`xception in thread "main" java.lang.UnsupportedClassVersionError: com/github/lindenb/jvarkit/tools/sam2tsv/Sam2Tsv : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`
I am not quite sure if this is the reason to the StopIteration issue. Will be looking forward to hear back from you on this. Thank you!

**Comment by Huanle** [comment]
Hi @BioinfoHub-PeiQinNg ,
Thanks for using epinano. 
May I know which version of `sam2tsv.jar` you are using? You are expected to use [the one](https://github.com/novoalab/EpiNano/blob/master/misc/sam2tsv.jar) included in the Epinano git repository. 
Hope this helps.

**Comment by BioinfoHub-PeiQinNg** [comment]
Hi Huan.

Thank you for replying. I have reinstalled the repo using `git clone https://github.com/novoalab/EpiNano` and reran the samtools command just to be sure I am using the current `sam2tsv.jar`.

It still gives the same error message. Any ideas how I can resolve this?

**Comment by Huanle** [comment]
Have you run 
`samtools view -h -F 3860 {bam_file} | java -jar {sam2tsv} -r {reference_file}` 
and see any outputs?

**Comment by BioinfoHub-PeiQinNg** [comment]
Hi Huan,

Yes I did. Still the same error message as the one I have posted.

I have attached the error message for reference
`samtools view -h -F 3860 H10_Heads_R1_RNAD.bam  | java -jar  /home/ng/localenv/EpiNano/misc/sam2tsv.jar  -r /data/processing1/sabrina_ng/ref/genome.fasta
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/lindenb/jvarkit/tools/sam2tsv/Sam2Tsv : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

**Comment by Huanle** [comment]
Hi @BioinfoHub-PeiQinNg ,

this seems to be an [error ](https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0)associated with Java version. 
I recommend updating your java and try again.

**Comment by BioinfoHub-PeiQinNg** [comment]
Yep! That fixes it! Thank you
